version: "3.9"  # optional since v1.27.0
services:
  bot:
    image: python:3.9-alpine
    container_name: repost-bot-ripoff
    working_dir: /app
    env_file: .env
    volumes:
      - ./CompareImageHashes:/app/CompareImageHashes
      - ./HashDatabase:/ap/HashDatabase
      - ./PyGoogleImgReverseSearch:/app/PyGoogleImgReverseSearch
      - ./rStuff:/app/rStuff
      - ./info.py:/app/info.py
      - ./main.py:/app/main.py
      - ./strings.py:/app/strings.py
      - ./MainWorker.py:/app/MainWorker.py
      - ./HashCollector.py:/app/HashCollector.py
    networks:
      - net

networks:
  net:
    driver: bridge