version: "3.8"
services:
  hoarder:
    init: true
    build:
      context: .
      target: base-stage
    image: kgbtrbot-hort:hoarder
    container_name: kgbtrbot-hort-hoarder
    working_dir: /app
    restart: on-failure
    env_file: .env
    volumes:
      - ./src/:/app/
    networks:
      - net
    command: python hoarder.py

  main:
    init: true
    build:
      context: .
      target: base-stage
    image: kgbtrbot-hort:main
    container_name: kgbtrbot-hort-main
    working_dir: /app
    restart: on-failure
    env_file: .env
    volumes:
      - ./src/:/app/
    networks:
      - net
    command: python main.py

networks:
  net:
    driver: bridge